student:
  name: lhx
  age: 18

type: java

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    enabled: true
#  mvc:
#    view:
#      prefix: /pages/
#      suffix: .jsp
#    static-path-pattern: /**
#  resources:
#      static-locations: classpath:/resources/,\
#                          classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    #schema: database/import.sql
    #sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect


#logging:
#  level:
#    xatu.zsl: debug
#    org.springfromework.web: info
#    org.hibernate: error
#  file: log\myspringboot.log









